spring:
  application:
    name: my-shop-service-content-provider
  datasource:
    druid:
      url: jdbc:mysql://192.168.31.66:3306/my-shop?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8502

mybatis:
  type-aliases-package: com.zgy.my.shop.commons.domain
  mapper-locations: classpath:mapper/*.xml

services:
  versions:
    content:
      v1: 1.0.0

dubbo:
  scan:
    base-packages: com.zgy.my.shop.service.content.provider.api.impl
  application:
    id: my-shop-service-content-provider
    name: my-shop-service-content-provider
    qos-port: 22223
    qos-enable: true
  protocol:
    id: dubbo
    name: dubbo
    port: 20882
    status: server
    serialization: kryo
  registry:
    id: zookeeper
    address: zookeeper://192.168.31.104:2181?backup=192.168.31.104:2182,192.168.31.104:2183