spring:
  application:
    name: my-shop-service-user-consumer
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: utf-8
    servlet:
      content-type: text/html
server:
  port: 8601

services:
  versions:
    user:
      v1: 1.0.0

dubbo:
  scan:
    base-packages: com.zgy.my.shop.service.user.consumer
  application:
    id: my-shop-service-user-consumer
    name: my-shop-service-user-consumer
  protocol:
    id: dubbo
    name: dubbo
    serialization: kryo
    status: server
    port: 30881
  registry:
    id: zookeeper
    address: zookeeper://192.168.31.104:2181?backup=192.168.31.104:2182,192.168.31.104:2183
